### ISSUE TITLE
_.isArray

### ISSUE THREAD

**Issue by karolisgrinkevicius** [you-dont-need/You-Dont-Need-Lodash-Underscore#106]
Hi! Nice plugin! What about `_.isArray` rule which could be natively replaced by `Array.isArray`?

**Comment by stevemao** [comment]
@karolisgrinkevicius Please send us a PR. This also needs to add to the ESLint :)

**Comment by karolisgrinkevicius** [comment]
@stevemao PR is already created https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/pull/107.

**Comment by stevemao** [comment]
PR merged :)
