### ISSUE TITLE
_.reverse is marked as "lodash only" but there is a native implementation

### ISSUE THREAD

**Issue by cb504** [you-dont-need/You-Dont-Need-Lodash-Underscore#110]

**Comment by stevemao** [comment]
@cb504 Just send us a PR

**Comment by cjtaylor1990** [comment]
@stevemao I think there is a bit of confusion in your README:

<img width="939" alt="Screen Shot 2019-10-09 at 11 01 59 PM" src="https://user-images.githubusercontent.com/9288608/66535888-2cb74a80-eae9-11e9-91b1-68648aeda7cd.png">

**Comment by stevemao** [comment]
@cjtaylor1990 of course. Any improvements is welcome :)

**Comment by cjtaylor1990** [comment]
Issue handled in #223
