### ISSUE TITLE
Proposition for _.set equivalent 

### ISSUE THREAD

**Issue by iabotsiTC** [you-dont-need/You-Dont-Need-Lodash-Underscore#115]
Hi, 
Thank you for this repo, it gaves me lot of ideas to refactor my code. 
I would like to suggest a replacement for the `_.partial` method, using Rest and Spread operators of ES6: 

Create a function that calls _func_ with _args_.

  ```js
  // Lodash
  function greet(greeting, name) {
    return greeting + ' ' + name;
  }
  var sayHelloTo = _.partial(greet, 'hello');

  // Native
  function greet(greeting, name) {
    return greeting + ' ' + name;
  }
  var sayHelloTo = (...args) => greet('hello', ...args)
  ```

What do you think of it? Is there any flaw?

**Comment by stevemao** [comment]
Sounds good to me. PR welcome then.

**Comment by jwallet** [comment]
partial is on master, should be closed
