### ISSUE TITLE
lodash _.times

### ISSUE THREAD

**Issue by arnas** [you-dont-need/You-Dont-Need-Lodash-Underscore#117]
What about _.times function. There is es6 Array.from, which lets somewhat replicate that function.
`let out = Array.from(Array(10), (_,x) => x);`     

// [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

**Comment by stevemao** [comment]
PR welcome!

**Comment by jacktuck** [comment]
@edysegura Not quite, lodash optionally takes a `iteratee` so OPs solution fits i think.

**Comment by rockmandash** [comment]
My implementation using native `Array.from`
```javascript
const times = (n, fn) => {
  let firstReturn = fn(0);
  let fakeArray = Array.from({ length: n - 1 });

  if (firstReturn !== undefined) {
    return [
      firstReturn,
      ...fakeArray.map((item, index) => {
        return fn(index + 1);
      })
    ];
  } else {
    fakeArray.forEach((item, index) => {
      fn(index + 1);
    });
  }
};
```

**Comment by arnas** [comment]
Created pr https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/pull/150
