### ISSUE TITLE
missing _.assign in the rules

### ISSUE THREAD

**Issue by cht8687** [you-dont-need/You-Dont-Need-Lodash-Underscore#118]
missing _.assign in the rules

**Comment by lamhieu-vk** [comment]
what do you find? 

`https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_assign`

**Comment by lamhieu-vk** [comment]
I just update rules for Object _.assign, you can [read more here](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/pull/120)
