### ISSUE TITLE
Missing _.cloneDeep(value)

### ISSUE THREAD

**Issue by Kaesebrot84** [you-dont-need/You-Dont-Need-Lodash-Underscore#121]
There is no entry for [`_.cloneDeep(value)`] (https://lodash.com/docs/4.17.5#cloneDeep). I am not really sure  whether this makes any sense. But [here](https://dev.to/ptasker/best-way-to-copy-an-object-in-javascript-827) it is suggested that the following expression can clone (at least) objects.

```javascript
JSON.parse( JSON.stringify( obj ) );
```
For further information see [this StackOverflow question](https://stackoverflow.com/q/122102/7579291).
Should this be adapted into the list?

**Comment by stevenvachon** [comment]
That's not a complete replacement because JSON does not support other objects such as functions, dates and regular expressions.

**Comment by VitorLuizC** [comment]
```js
Object.create(null, Object.getOwnPropertyDescriptors(obj))
```

**Comment by EddyLuten** [comment]
@VitorLuizC it's still a shallow copy, not a drop in for deepClone:

```js
let x = { a: 1, b: 2 };
let y = { c: x, d: 3 };
let z = Object.create(null, Object.getOwnPropertyDescriptors(y));
z.c.a = 4;
// x is indirectly modified:
console.log(x);
// Object { a: 4, b: 2 }
```

I'd love to see a decent replacement for deepClone since it's one of the few reasons that lodash is still part of our codebase.

**Comment by stevemao** [comment]
I personally avoid any `cloneDeep`.

**Comment by gmbwa** [comment]
try JSON.parse(JSON.stringify(THE_OBJECT or THE_ARRAY))

**Comment by ouassimBenMosbah** [comment]
Here is a working solution insipred by the code in [this article](https://medium.com/@Farzad_YZ/3-ways-to-clone-objects-in-javascript-f752d148054d)

```typescript
function cloneDeepWithoutLodash(src) {
  let target = {};
  for (const prop in src) {
    if (src.hasOwnProperty(prop)) {
      if(src[prop] != null && typeof src[prop] === 'object') {
        target[prop] = cloneDeepWithoutLodash(src[prop]);
      } else {
        target[prop] = src[prop];
      }
    }
  }
 return target;
}

const source = {a: { b:2 }, c:3};
const target = cloneDeepWithoutLodash(source);
source.a.b = 100;
console.log(source.a.b); // 100
console.log(target.a.b); // 2
```

**Comment by stevenvachon** [comment]
I think this function is a reason to use lodash/underscore.

**Comment by crfrolik** [comment]
> I think this function is a reason to use lodash/underscore.

Wait, so you're saying I *do* need lodash/underscore?

Maybe this repo whould be named `You-Might-Not-Need-Lodash-Underscore`.

**Comment by zargold** [comment]
This should more or less work:

```
const recursiveClone = (src) => {
if (Array.isArray(src)) {
   return src.map(recursiveClone)
}
if (typeof src !== 'object') {
  return src
}
return Object.fromEntries(
  Object.entries(src).map(
    ([key, val]) => ([key, recursiveClone(val)])
  )
)
}
```

based on: @ouassimBenMosbah answer:
function cloneDeepWithoutLodash(src) {
  let target = {};
  for (const prop in src) {
    if (src.hasOwnProperty(prop)) {
      if(src[prop] != null && typeof src[prop] === 'object') {
        target[prop] = cloneDeepWithoutLodash(src[prop]);
      } else {
        target[prop] = src[prop];
      }
    }
  }
 return target;
}

**Comment by sukima** [comment]
@zargold solution should be in this repo for sure!! 👏

**Comment by Shiroh1ge** [comment]
For node.js this is a decent solution: 
```ts
import { deserialize, serialize } from 'v8';

deserialize(serialize(obj))
```

source: https://blog.logrocket.com/methods-for-deep-cloning-objects-in-javascript/

For Node v17.+ there is also ``structuredClone`` available

```ts
structuredClone(obj)
```

**Comment by VitorLuizC** [comment]
@Shiroh1ge won't work for functions and other value types.
