### ISSUE TITLE
_.each for Collections

### ISSUE THREAD

**Issue by shhac** [you-dont-need/You-Dont-Need-Lodash-Underscore#125]
Can be achieved with `Object.entries` and `arr.forEach`

```js
const collection = {foo: 'a', bar: 'b', baz: 'c'};
Object.entries(collection).forEach(([key, value], index) => {
    console.log(key, value, index);
});
// => "foo" "a" 0
// => "bar" "b" 1
// => "baz" "c" 2
```

This pattern also works on _Array_ (though I don't know why you'd use it over a regular `.forEach` for that)

**Comment by aalfiann** [comment]
Object.entries is available in ES7 so you might getting error when use it in NodeJS6.

**Comment by stevemao** [comment]
@aalfiann as long as we specify the right browser support it should be fine.

**Comment by cjtaylor1990** [comment]
@aalfiann Seems like Node 7 supports it https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries

**Comment by cjtaylor1990** [comment]
@stevemao Want me to handle this one? I can put it in the README, rules, and tests.

**Comment by stevemao** [comment]
@cjtaylor1990 Would be great. Thanks!

**Comment by cht8687** [comment]
#231
