### ISSUE TITLE
Collection iteration on objects works as well

### ISSUE THREAD

**Issue by truongsinh** [you-dont-need/You-Dont-Need-Lodash-Underscore#131]
```js
const sample = { 'a': 1, 'b': 2 };
_.each(sample, function(value, key) {
  console.log(key, value);
});

Object.entries(sample).forEach(([key, value]) => {
  console.log(key, value);
})
// => Logs 'a' then 'b' (iteration order is not guaranteed).
```
Although the browser support may vary, and some people don't like the verboseness. Is this something worth mentioned? I'm happy to make PR

**Comment by ODudek** [comment]
![entries](https://user-images.githubusercontent.com/20043951/46085720-ed9cac80-c1a6-11e8-81b3-f507e282a641.jpg)
Support for `entries`. I think you can make PR for it.

**Comment by cjtaylor1990** [comment]
This was handled in #231.
