### ISSUE TITLE
flat/flatten update

### ISSUE THREAD

**Issue by nebulousdog** [you-dont-need/You-Dont-Need-Lodash-Underscore#145]
to add to the [`_.flatten`](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_flatten) example, there is a native `flat`.

supplemental: 
* https://alligator.io/js/flat-flatmap/
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat
* https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/esnext.array.flat.js

**Comment by jwallet** [comment]
> This is an experimental API that should not be used in production code.

**Comment by styfle** [comment]
This is no longer experimental and has been standardized.

Browser support looks pretty good too.

<img src="https://user-images.githubusercontent.com/229881/61815211-becb8300-ae17-11e9-8537-5e15b8416eb2.png" width="300" />

**Comment by nebulousdog** [comment]
@styfle hooray

![image](https://user-images.githubusercontent.com/2218331/61817754-1cee6b00-ae04-11e9-8a30-f6ae0d18c278.png)

https://tc39.es/proposal-flatMap/#sec-Array.prototype.flat

**Comment by stevemao** [comment]
Please send a PR

**Comment by cjtaylor1990** [comment]
@stevemao @cht8687 I noticed that they did a PR where they added it in the README file, but not in the rules or the tests. Want me to handle this?

**Comment by cht8687** [comment]
@cjtaylor1990 

Go ahead! 👍

**Comment by cjtaylor1990** [comment]
Addressed in Pull Request #228
