### ISSUE TITLE
fix(uniq): incompatible with Internet Explorer

### ISSUE THREAD

**Issue by yarnball** [you-dont-need/You-Dont-Need-Lodash-Underscore#157]
Hi

Firstly- great repo.

I've found an issue with `_.uniq` and Internet Explorer (IE). In your docs, it says your example supports IE. It does not., it IE does not support `new Set(iterable)`

See screenshot from `mdn` below:
![screen shot 2018-11-30 at 11 30 03 am](https://user-images.githubusercontent.com/13043067/49261416-39fdb480-f496-11e8-8a4b-e2d6669de3b9.jpg)

So, in the example for `uniq` we could change:
```
[...new Set(array)];
```

to...
```
 array.filter((v, i, a) => a.indexOf(v) === i)
```

I'm happy to create a PR for this (but don't have access to this repo).

**Comment by stevemao** [comment]
PR welcome to add it

**Comment by yarnball** [comment]
Cheers, done 

#158
