### ISSUE TITLE
_.get example is broken

### ISSUE THREAD

**Issue by clujin** [you-dont-need/You-Dont-Need-Lodash-Underscore#178]
The current native implementation of `get` is broken in the example:

```
  // Native
  const get = (obj, path, defaultValue) => path.split(".")
  .reduce((a, c) => (a && a[c] ? a[c] : (defaultValue || null)), obj)
  
  var object = { a: [{ b: { c: 3 } }] };
  var result = get(object, 'a[0].b.c', 1); 
  // output: 3
```

The `split` currently doesn't deal with the `[]` notation. In fact, it skips a subclass of cases were the path is nothing but brackets `[0][1]`.

Also another minor issue is that `a[c]` may return a falsey value of `0` which will return the defaultValue instead of `0`.

**Comment by cht8687** [comment]
thanks! 👍
