### ISSUE TITLE
_.omit when property name comes from variable

### ISSUE THREAD

**Issue by jakubzloczewski** [you-dont-need/You-Dont-Need-Lodash-Underscore#180]
Any ideas how to replace _.omit when property name is from variable?

```
var object = { 'a': 1, 'b': '2', 'c': 3 };

// Underscore/Lodash
var propertyNameToRemove = 'a';
var result = _.omit(object, [propertyNameToRemove]);
console.log(result)
// output: { 'b': '2', 'c': 3 }

// Native
'???';
```

**Comment by fabiomcosta** [comment]
@jakubzloczewski this worked for me:

```js
var object = { 'a': 1, 'b': '2', 'c': 3 };
const propertyNameToRemove = 'a';
const { [propertyNameToRemove]: b, ... result } = object;
console.log(result);
```

**Comment by stevemao** [comment]
PR welcome

**Comment by fabiomcosta** [comment]
@stevemao I think this issue can be closed TBH, it was more of a question.
Or did you think this should be documented?

**Comment by stevemao** [comment]
Either way is fine with me. If anyone wants to improve the docs PR welcome :)

**Comment by kevinrodriguez-io** [comment]
Just to add to this thread:

In this scenario:
```
var object = { 'a': 1, 'b': '2', 'c': 3 };
const propertyNameToRemove = 'a';
const { [propertyNameToRemove]: b, ... result } = object;
console.log(result);
```

```
[propertyNameToRemove]: b
```
Can be anything, like: `[propertyNameToRemove]: _` or `[propertyNameToRemove]: $`

**Comment by tvedtorama** [comment]
I did the following, in Typescript, to support lists of properties to remove:

```typescript
export const omit = <T, Y extends keyof T>(item: T, elms: Y[]): Omit<T, Y> => elms.reduce((x, y) => (({[y]: _d, ...rest}) => rest)(x), item)
```

I can't guarantee that this is neither the most efficient, nor the most true to the lodash implementation, but it's simple and seems to work.
