### ISSUE TITLE
_.times doesn't entirely match lodash behaviour

### ISSUE THREAD

**Issue by GeorgeWL** [you-dont-need/You-Dont-Need-Lodash-Underscore#181]
There's a secondary usage which is quite commonly used, such as to populate an array for tests, of 
```ts
_.times(iterate:number, func:()=>void)
```
that I've seen used before, to have it run the same function a set number of times.

**Comment by stevemao** [comment]
PR welcome

**Comment by GeorgeWL** [comment]
I'll think about a way to mirror that and PR when I have.

**Comment by cht8687** [comment]
@GeorgeWL any update on this 😄 ?

**Comment by GeorgeWL** [comment]
I gave up ha

**Comment by cht8687** [comment]
@GeorgeWL 😢

**Comment by cjtaylor1990** [comment]
@GeorgeWL Could this be accomplished with either the .forEach or .map Array methods?

**Comment by GeorgeWL** [comment]
I believe so yeah

I'll quickly try in node. To get the exact behaviour you'd probably have to make a custom function that if it has a second argument does for each, else does the map.

**Comment by GeorgeWL** [comment]
https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/pull/222

**Comment by cjtaylor1990** [comment]
@GeorgeWL Did you conclude this wasn't an Issue? If so, we can close the issue.
