### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ovidiubute** [you-dont-need/You-Dont-Need-Lodash-Underscore#190]
Hi guys,

Just wanted to better understand what is the release process like. I'm looking at the GitHub releases section and it's been around a year since the last one. There have been a lot of new functions added since then, so when do you plan on cutting a new release from the master branch?

Thanks

**Comment by ovidiubute** [comment]
Any thoughts on when you'll release a new version to npm?

**Comment by stevemao** [comment]
Done. Thanks
