### ISSUE TITLE
Add `isNil` to eslint plugin

### ISSUE THREAD

**Issue by fabiomcosta** [you-dont-need/You-Dont-Need-Lodash-Underscore#196]
Similarly to `isUndefined` and `isNull`, `isNil` is pretty easy to implement and we should probably add to the eslint plugin.

Is there any argument agains that?

Past related issues: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/issues/132

**Comment by stevemao** [comment]
PR welcome.
