### ISSUE TITLE
Underscore.js OOP style doesn't report as negative

### ISSUE THREAD

**Issue by Dentxinho** [you-dont-need/You-Dont-Need-Lodash-Underscore#208]
The rules only report negatives when using Undercore's functional style. 
When using [OOP Style](https://underscorejs.org/#oop) it doesn't work:

![image](https://user-images.githubusercontent.com/1199765/60688206-1fefde80-9e8a-11e9-9e52-3fbf3771b27c.png)

**Comment by stevemao** [comment]
@Dentxinho PR welcome

**Comment by cjtaylor1990** [comment]
I'll try my hand at fixing this, assuming that this is still an issue.

**Comment by stevemao** [comment]
Yes it is :)

**Comment by cjtaylor1990** [comment]
I think I figured it out. I'll push soon. It's essentially a weird case where the OOP style doesn't read quite right (essentially, there's a deeper layer inside of the callee object that holds the _ name). It ends up being callee.object.callee.name rather than just callee.object.name.

**Comment by cjtaylor1990** [comment]
Okay, just submitted a pull request. Hopefully everything looks good on your end. If it doesn't, just tell me and I can try some more.
