### ISSUE TITLE
Module support not working

### ISSUE THREAD

**Issue by stevenvachon** [you-dont-need/You-Dont-Need-Lodash-Underscore#212]
This asserts a lint error:
```js
import * as _ from 'lodash';
_.isArray([]);
```
…while this does not:
```js
import {isArray} from 'lodash';
isArray([]);
```

Here's my config:
```js
extends: [
	'eslint:recommended',
	'plugin:you-dont-need-lodash-underscore/all'
],
plugins: [
	'jsdoc',
	'sort-destructure-keys',
	'you-dont-need-lodash-underscore'
],
rules: {
	'you-dont-need-lodash-underscore/is-array': 2
}
```

Per #98, this should be working.

**Comment by stevenvachon** [comment]
Ah, there was never a release for that PR. Please make a `6.6.0` release!

**Comment by cht8687** [comment]
@stevemao we can have `6.6.0` release now.

**Comment by cht8687** [comment]
@stevenvachon  
Hi Steven, please check the new release.
https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/releases/tag/v6.6.0

**Comment by cht8687** [comment]
closing this for now.

**Comment by stevenvachon** [comment]
@cht8687 thanks!
