### ISSUE TITLE
When DO you need lodash?

### ISSUE THREAD

**Issue by derek-adair** [you-dont-need/You-Dont-Need-Lodash-Underscore#217]
Maybe a bit silly; but it could be an interesting bit of contrast to show which methods you actually MAY NEED underscore or lodash for!

Cool project by the way.

**Comment by BlueRaja** [comment]
When it makes the code easier to read.  Which is, ironically, most of the use-cases shown on this page.  Like seriously, who in their right mind would think that
```
[x,y].reduce((a, b) => a.filter(c => !b.includes(c)))
```
is an acceptable replacement for
```
_.difference(x,y)
```

**Comment by aalfiann** [comment]
When you are working in a team which is your code must be easy to read and when you dont worry about the performance.

**Comment by stevemao** [comment]
I suggest you to look at ramda, which has more functional utils.

**Comment by derek-adair** [comment]
@stevemao  - So... when you think you "need" lodash just use ramda?  It seems like *exactly* what I want out of lodash!

Why *I* use lodash...

1. Immutable methods (which not all of them are D:)
2. Null safe methods
3. Easy to read

To me it seems like, as a javascript dev, I want to balance readability with performance.  Taking @BlueRaja 's example - i'd MUCH prefer _.difference, assuming it's performance is close.  It'd be very compelling to provide unbiased benchmarks for these methods in order to better judge which methods are "more ok" than others. 

It seems like the reasons to not use a method could be categorized to provide more thorough assessment.

--------
Also, trying to think ahead; Are there reasons not to use Ramda?

**Comment by stevemao** [comment]
I feel ramda is a much better functional programming helper lib. It follows fantasy land spec so works with libs like sanctuary out of the box.

**Comment by dietergeerts** [comment]
> When you are working in a team which is your code must be easy to read and when you dont worry about the performance.

Lodash is in most cases better in performance than the native way!
