### ISSUE TITLE
_.forEach gives incorrect suggestion for objects

### ISSUE THREAD

**Issue by cjtaylor1990** [you-dont-need/You-Dont-Need-Lodash-Underscore#229]
I was trying to make a PR in response to #125, and I found out that the linter doesn't distinguish between arrays and objects when fed into lodash functions, and therefore, will give incorrect advice.

For example, if you use eslinter with the plugin, and give it a file with something like this:
```
const _ = require('lodash');

let a = {
	first: 1,
	second: 2,
	third: 3,
}

_.forEach(a, item => {console.log(item)});
_.each(a, item => {console.log(item)});
```
would give,
```
   9:1   warning  Consider using the native Array.prototype.forEach()  you-dont-need-lodash-underscore/for-each
  10:1   warning  Consider using the native Array.prototype.forEach()  you-dont-need-lodash-underscore/each
```
Since our variable is an object without a .forEach() method, the suggested change results in an error.

**Possible solution**: since the linter goes off of function rather than the full context of its use, perhaps it would be possible to use a longer alternative suggestion. For example:

`Consider using native Array.prototype.forEach() or Object.entries().forEach()`

The other native alternative comes from #125

**Comment by cht8687** [comment]
#231
