### ISSUE TITLE
Rule for _.throttle

### ISSUE THREAD

**Issue by cupofjoakim** [you-dont-need/You-Dont-Need-Lodash-Underscore#235]
It seems that in my company much of the usecase for lodash is the `_.throttle`-function. It's kind of easy to do without lodash, but is kind of a meaty function compared to the others in this repo. My current implementation is 13 lines, so It'd be the biggest here (one more line than the debounce alternative)

I can do a PR if wanted.

**Comment by stevemao** [comment]
@cupofjoakim PR welcome

**Comment by cjtaylor1990** [comment]
@cupofjoakim  This is actually relevant to some of the discussion on #227 when talking about longer native implementations. I think putting it in the README.md and then having the linter point the user towards the README would be good. Just my thoughts on the issue.

**Comment by cupofjoakim** [comment]
@cjtaylor1990 I'll try to make a PR tonight if I have time :)
