### ISSUE TITLE
Add alternatives for isString / isFunction

### ISSUE THREAD

**Issue by hongaar** [you-dont-need/You-Dont-Need-Lodash-Underscore#240]
- `_.isFunction(x)` could be written as `typeof x === 'function'` (https://stackoverflow.com/a/17108198/938297)
- `_.isString(x)` could be written as `typeof x.valueOf() === 'string'` (https://stackoverflow.com/a/58892465/938297)

Would be happy to create 2 PR's for these if this is something you'd like to add.

**Comment by stevemao** [comment]
@hongaar yes please

**Comment by hongaar** [comment]
Closed because
- _.isString is already added (PRs are open with some tweaks #285, #288)
- PRs are open for _.isFunction (#259, #289)
