### ISSUE TITLE
About _.get with . (dot) in object keys

### ISSUE THREAD

**Issue by griinem** [you-dont-need/You-Dont-Need-Lodash-Underscore#242]
Hi,

Today I've found that `_.get` doesn't work with objects that contains . (dot) in keys. For example:
```
get({'a.b': 1}, 'a.b')
// => undefined
```
Lodash can handle this nicely:
```
get({'a.b': 1}, 'a.b')
// => 1
```

What is your opinion about this? Personally I don't think this behavior is intentional. Am ready if PR needed.

P/s: For cases like `{'a.b': {'c.d': 1}}`, lodash can handle that as well:
```
get({'a.b': {'c.d': 1}}, ['a.b', 'c.d'])
// => 1
```

**Comment by stevemao** [comment]
PR welcome :)

**Comment by rubiin** [comment]
you can do a pr
