### ISSUE TITLE
Need npm release

### ISSUE THREAD

**Issue by kaflan** [you-dont-need/You-Dont-Need-Lodash-Underscore#253]
Release required in npm. So it will be easier to work with useful features

**Comment by kaflan** [comment]
@stevemao 
Is npm release possible? After all, people use lodas and other helpers because they don’t know the script, but because it’s so simpler?

**Comment by cjtaylor1990** [comment]
@kaflan The plugin is on npm: https://www.npmjs.com/package/eslint-plugin-you-dont-need-lodash-underscore

**Comment by stevemao** [comment]
Done :)
