### ISSUE TITLE
isString fails on empty string

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [you-dont-need/You-Dont-Need-Lodash-Underscore#304]
Just tracked down a bug in my code and realized it's caused by isString() failing on an empty string and returning false when it actually is a string.  This is contrary to my expectations of what "isString" function would do, am I correct in thinking this?

This is the function listed here: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_isString
```
// Native
function isString(str){
  if (str && typeof str.valueOf() === "string") {
    return true
  }
  return false
}
```

And it fails due to the ```if(str``` bit at the start because an empty string is always false due to ECMA standard:

> 
> ToBoolean
>  The result is false if the argument is the empty String (its length is zero); otherwise the result is true

I quickly resolved it by just checking if it's null explicitly first and then if it's an empty string explicitly second as early short circuits then resuming the rest of the code but without the check if str is truthy.

**Comment by mrgenixus** [comment]
consider the much simpler:
```
function isString(str) {
  return str != null && typeof str.valueOf() === "string"
}
```
