### ISSUE TITLE
DEP0128 DeprecationWarning

### ISSUE THREAD

**Issue by emfomy** [you-dont-need/You-Dont-Need-Lodash-Underscore#317]
I'm using Node v16 and I got the following warning while running ESLint.

```
(node:13459) [DEP0128] DeprecationWarning: Invalid 'main' field in './node_modules/eslint-plugin-you-dont-need-lodash-underscore/package.json' of 'lib/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by ehmicky** [comment]
PR at #315 to fix this.

**Comment by ehmicky** [comment]
@cht8687 Would it be possible to make a new release on npm? Thanks!

**Comment by cht8687** [comment]
@ehmicky 
I think it has been released in https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/releases/tag/v6.12.0

**Comment by ehmicky** [comment]
Oh, right. Thanks!
