### ISSUE TITLE
Equivalent of _.without

### ISSUE THREAD

**Issue by slorber** [you-dont-need/You-Dont-Need-Lodash-Underscore#33]
Hi,

Is there an elegant way to remove an item from an array in an immutable way without using underscore?

I want `_.without([1,2,3],2)` to return `[1,3]`. 

The original array should remain unmodified.

I'd like to avoid using a syntax involving indexes, slice, splice or whatever because I never remember it and using _ is much simpler.

Is there any simple way with ES next?

**Comment by tuckerconnelly** [comment]
This is probably the closest:
```js
[1,2,3].filter(({el, i, arr}) => !arr.includes(el))
```

**Comment by slorber** [comment]
yes thanks

still quite heavy imo :'(

**Comment by slorber** [comment]
btw I'll have the same question for _.omit :)

**Comment by tuckerconnelly** [comment]
Hmm, a for...in loop would probably be easiest. But here's a one-liner using the es6 stuff:

```js
const object = { a: 1, b: '2', c: 3 };

Object.keys(object).filter(i => ['a', 'c'].includes(i)).reduce((prev, cur) => { ...prev, [cur]: object[cur] }, {})
```

**Comment by slorber** [comment]
lol
i think i'll keep using lodash for now :)

**Comment by AndreasHassing** [comment]
This should also work (and is immutable):
```javascript
var myArray = [1,2,3];

var filteredArray = myArray.filter(i => i !== 2)
console.log(filteredArray); // => [1, 3]
console.log(myArray);       // => [1, 2, 3]

// Helper function
Array.prototype.without = function(value) {
  return this.filter(i => i !== value);
}

console.log(myArray.without(2)); // => [1, 3]
```

**Comment by slorber** [comment]
@AndreasHassing does not support passing an array, unlike solution of https://github.com/cht8687/You-Dont-Need-Lodash-Underscore/issues/33#issuecomment-195823281

**Comment by AndreasHassing** [comment]
@slorber wouldn't this work as wanted: `[1, 2, 3].without(2);`?

**Comment by slorber** [comment]
I want to do what lodash do, and yes it supports array

**Comment by stevemao** [comment]
Can we close this issue?

**Comment by tracker1** [comment]
It's a pretty easy oneliner for without...

    const without = (array, filtered) => array.filter(n => n != filtered);

    without([1,2,3], 2); // [1,3]

Stuff like this, I'll just inline at the top of the relevant script, as import boilerplate is often bigger than the snippet.

**Comment by stevemao** [comment]
PR welcome to add this :)
