### ISSUE TITLE
Warning for isEmpty in WebStorm

### ISSUE THREAD

**Issue by straurob** [you-dont-need/You-Dont-Need-Lodash-Underscore#346]
Refers to:
https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_isempty

```javascript
const isEmpty = (obj) => [Object, Array].includes((obj || {}).constructor) && !Object.entries((obj || {})).length;
```

While this actually seems to work fine as code, WebStorm (2022.1.3) gives me the following warning and I wonder if this is a WebStorm issue or if there is possible something "wrong" with the code?

```
Argument type Function is not assignable to parameter type ObjectConstructor | ArrayConstructor
Type Function is not assignable to type ArrayConstructor
Assigned type doesn't contain call signatures
```

**Comment by Cowjiang** [comment]
You can infer the parameter 'obj'  to the 'any' type
like this:
`const isEmpty = (obj: any) => [Object, Array].includes((obj || {}).constructor) && !Object.entries((obj || {})).length;`

**Comment by straurob** [comment]
> You can infer the parameter 'obj' to the 'any' type

This seems to be only valid for Typescript, right? Sorry, I forgot to mention that I'm using Vanilla JavaScript.

**Comment by Cowjiang** [comment]
> 
Let's see the declaration of 'Array.includes':
```typescript
interface Array<T> {
    /**
     * Determines whether an array includes a certain element, returning true or false as appropriate.
     * @param searchElement The element to search for.
     * @param fromIndex The position in this array at which to begin searching for searchElement.
     */
    includes(searchElement: T, fromIndex?: number): boolean;
}
```

And the declaration of 'Object.constructor':
```typescript
interface Object {
    constructor: Function;
}
```

And Webstorm show this:
```typescript
Array<ObjectConstructor | ArrayConstructor>.includes(searchElement: ObjectConstructor | ArrayConstructor, fromIndex?: number): boolean
```

That means Generics '<T>' was identified as '<ObjectConstructor | ArrayConstructor>', and that's why Webstorm will show the warning 'Argument type Function is not assignable to parameter type ObjectConstructor | ArrayConstructor'.

Umm, this warning doesn't show in VS Code. And if you change the Javascript Version to Flow in Webstorm, it won't show too.

**Comment by straurob** [comment]
I'll check the WebStorm issues if there is something similar. It obviously looks more like a WebStorm thing.
