### ISSUE TITLE
Default ESLint configs

### ISSUE THREAD

**Issue by pmcelhaney** [you-dont-need/You-Dont-Need-Lodash-Underscore#53]
Now that individual ESLint rules have been broken out (+1, very nice work Steve!) we should add some default [configs](http://eslint.org/docs/developer-guide/working-with-plugins#configs-in-plugins) so that folks don't have to configure each individual rule.

I'm thinking we can provide a few options:
- you-dont-need-lodash-underscore:all (all rules set to warn)
- you-dont-need-lodash-underscore:all-strict (all rules set to error)
- you-dont-need-lodash-underscore:safe (rules in which the native implementation exactly matches the _ one are set to warn)
- you-dont-need-lodash-underscore:safe-strict (rules in which the native implementation exactly matches the _ one are set to error, the rest are set to warn)

What do you think? I'll go ahead and get a pull request started.

**Comment by cht8687** [comment]
sounds a good idea Pat. @stevemao  thoughts?

**Comment by stevemao** [comment]
Good idea!

**Comment by stevemao** [comment]
Maybe another config to error on rules in which the native implementation exactly matches the _ ones but warn on rules that could be replaced by native?

**Comment by stevemao** [comment]
> rules in which the native implementation exactly matches the _ one

I think this could mean two things:
1. signature of the function is exactly the same but the implementation might be different
2. `_` uses the native method

I tend to favour the first definition here for this module.

**Comment by pmcelhaney** [comment]
Yes, if I understand correctly, that's what I would probably want as a default. Error if I know I can replace the _ function with a native function that works the same way. Warn if I may or may be able to switch to native depending on the use case. 

That's the config I called safe-strict. I'm  not crazy about that particular name. If we put our heads together I bet we can come up a useful set of config options and a more intuitive naming scheme.

**Comment by pmcelhaney** [comment]
I would say if the contracts match. For any given input the _ and native functions will produce the same output. I *think* that's what you meant by signature but want to be sure.

**Comment by pmcelhaney** [comment]
BTW, the settings for the "compatible" flag at the moment may not strictly match any of these definitions. We need to review each rule carefully with respect to whether the native function is truly compatible with the _ function.

**Comment by stevemao** [comment]
signature I mean the type of the parameters and return value are exactly the same. And it does exactly the same thing as the native method. The internal implementation/performance might be different.
A lot of array methods are not. EG: because `_` uses a stripped-down version of loop so it gains performance but doesn't work with sparse arrays.

**Comment by stevemao** [comment]
> That's the config I called safe-strict.

Sorry yes, I misread your comment.

**Comment by pmcelhaney** [comment]
Yeah, I can see how people might want to slice "compatibility" different ways:

1. As long as I can swap out the _ function with the native function and know my code won't break, I'm happy. I'm not concerned about sparse arrays because I don't use them (at least not intentionally).

2. I don't consider the native and _ to be compatible unless they behave exactly the same way for *all* inputs (including edge cases such as sparse arrays).

3. I don't want to swap the _ function with the native function unless I know I have nothing to lose by doing so. If the _ is more efficient (because it doesn't deal with edge cases like sparse arrays), I want to keep it.

Personally, I favor #1. If you and @cht8687 agree, maybe we just run with that. At least for now. We can always come back and add more fields to the JSON file to denote the ramifications of switching from _ to native.

**Comment by stevemao** [comment]
For a future smarter version, the linter should error/warn on `_.forEach(array)` but not `_.forEach(object)` (at least a different message) etc.

**Comment by pmcelhaney** [comment]
I've given it some more though and opened #57 and #58. Before we set any default configs, it makes sense to flesh out the options of the individual rules. There's an opportunity to add more nuance than simply which rules are warnings and which are errors.

**Comment by mockdeep** [comment]
Would love to have an `all` that defaults to `error` and any reasonable default config. This is similar to [`eslint:all`](https://github.com/eslint/eslint/blob/master/conf/eslint-all.js) and [`plugin:react/all`](https://github.com/yannickcr/eslint-plugin-react/blob/master/index.js). I'm happy to selectively disable or configure things myself.

**Comment by Vadorequest** [comment]
Really good idea, I just found out about this repo and I was wondering how to setup all rules to errors in a simple way.

**Comment by onethread** [comment]
It's not clear to me how to enable these alternate configurations. Perhaps it's the colon. Is it supposed to be like so:

```
  "extends": ["plugin:you-dont-need-lodash-underscore/all"],
```

When I do that, I'm still getting error reports vs warns.
