### ISSUE TITLE
You DO need Lodash

### ISSUE THREAD

**Issue by pmcelhaney** [you-dont-need/You-Dont-Need-Lodash-Underscore#57]
As @stevemao and others have brought to my attention, there are cases where Lodash provides advantages over the native library. They can provide more consistency across implementations, better performance in typical real world use, or both.

Therefore I think the ESLint plugin should provide options to encourage changing native functions to _ equivalents. Similar to how the [no-semi](http://eslint.org/docs/rules/semi) rule provides options to either require semicolons or disallow them.

**Comment by cht8687** [comment]
I agree with you. As long as we are helping developers. :+1:

**Comment by cht8687** [comment]
So in this case, our plugin is dynamic, can be configured to either alternatives => Lodash or Lodash => alternatives, is that what you are suggesting? @pmcelhaney

**Comment by pmcelhaney** [comment]
Yes. What I like about this repo is it educates me on the advantages and drawbacks of using a library like Underscore, et. al. 

Using a linter helped me get up to speed with ES6 very quickly. I'm keenly interested in [the synergy between linting and learning](https://github.com/eslint/eslint/issues/6582).

**Comment by mathieumg** [comment]
@pmcelhaney https://github.com/wix/eslint-plugin-lodash#preference-over-native

**Comment by stevemao** [comment]
I think https://github.com/wix/eslint-plugin-lodash#preference-over-native provides a good solution for this. Reopen this if you disagree.
