### ISSUE TITLE
Shimering all not-yet-available functions natively

### ISSUE THREAD

**Issue by aug-riedinger** [you-dont-need/You-Dont-Need-Lodash-Underscore#60]
Glad to find out about this project. I was actually thinking of doing something similar lately.

For a while, people installed LoDash to have access to functions like `_.map()`, `_.reduce()` etc.

I have never been sure about this, but I think those library did not modify the `Array` object inner methods through `Array.prototype.map = function() {}` to avoid conflicts with the possibly existing native method. Am I correct?

Well, I think the time has now come to actually do this.

Imagine a lib, that would look at the existing native methods in the current JS engine, and extend its JS capacities with all the non-existing ones.

The point would be to actually increase JS capacities so that devs start using them, and then letting some time to the ECMA community to integrate those methods natively. This would also prevent some risible fails like the [NPM LeftPad Package issue](http://www.haneycodes.net/npm-left-pad-have-we-forgotten-how-to-program/).

Would it make sense as project? Are there any pros/cons in doing this?

It would start with something like:

```
Array.prototype.map = Array.prototype.map || function(iteratee) {
    // LoDash Code
      var index = -1,
        result = Array(this.length);

    while (++index < this.length) {
      result[index] = iteratee(this[index], index, this);
    }
    return result;
}

Array.prototype.sum = Array.prototype.sum || function() {
  this.reduce(function(sum, el, i) {
    if (el.isNumber())
      return el + sum;
    return sum;
  }, 0);
}
```

JS is just about to be a great language, why not living in the future already?

**Comment by stevemao** [comment]
There are already [projects](https://github.com/es-shims/es5-shim)

**Comment by DanCouper** [comment]
Also,

a. `class MySuperDuperArray extends Array {}` is now a thing, if lacking in support a bit, and
b. if the bind operator is okayed, need/want to faff on with extending prototypes so as to retain the same semantics becomes moot - `['a', 'b']::zip(1, 2)` => `[['a', 1], ['b', 2]]`, `'Hello World'::kebabCase()` => `'hello-world'`
