### ISSUE TITLE
Definitions not found for multiple methods

### ISSUE THREAD

**Issue by noderat** [you-dont-need/You-Dont-Need-Lodash-Underscore#65]
I'm getting errors including what looks to be valid rules. Errors are occurring for these rules: findIndex, indexOf, lastIndexOf, forEach, reduceRight, after, isNaN, extendOwn, toLower, toUpper

```
warning  Definition for rule 'you-dont-need-lodash-underscore/indexOf' was not found  you-dont-need-lodash-underscore/indexOf
```

**Comment by cht8687** [comment]
@noderat  opps~ I had a quick look and found it is used kebab-case for exporting the rules...
I am fixing it now. Thanks for reporting it.

**Comment by stevemao** [comment]
See the docs

```
'plugins': ['you-dont-need-lodash-underscore'],
'rules': {
  'you-dont-need-lodash-underscore/for-each': 1,
  'you-dont-need-lodash-underscore/concat': 1,
  ...
}
```

**Comment by noderat** [comment]
@stevemao Ah, missed that since I was using the rule definition JSON to determine which rules applied since they weren't all explicitly laid out. camelCase is probably a better idea, since it matches the method names.

**Comment by stevemao** [comment]
@noderat 

> The rule names, by convention, should be dash-cased. is-nan should be the only bug here.  
See http://eslint.org/docs/rules/ or other eslint addons.

**Comment by noderat** [comment]
Ah, indeed! Should explicitly mention the name of the rule in the README.md then to prevent future confusion

**Comment by stevemao** [comment]
@noderat PR welcome. I agree it's not terribly obvious :)

**Comment by noderat** [comment]
@stevemao Looks like the rule for `_.after` doesn't exist still but is in the README.

**Comment by stevemao** [comment]
@noderat please open an issue for other problems. Thanks :)
