### ISSUE TITLE
What are the checkmarks for?

### ISSUE THREAD

**Issue by impressivewebs** [you-dont-need/You-Dont-Need-Lodash-Underscore#72]
Maybe this is a dumb question, but next to the browser version numbers, there are sometimes checkmarks, sometimes not. Fore example:

https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#browser-support-2

Why does the Firefox version have a checkmark, but not Chrome or Safari? I couldn't find anything in the page to explain this. Although I did mostly just skim, so my bad if I missed it. Maybe add an explanation for that, if it is indeed indicating something specific about browser support.

BTW great little reference, thanks!

**Comment by stevemao** [comment]
I think they are just missing @cht8687 ? @impressivewebs Thanks for reporting. PR welcome!

**Comment by cht8687** [comment]
yep. They are missing sicne this commit https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/commit/bdb702775ea1a31d4573804458afe56825b32539
