### ISSUE TITLE
very useful lodash functions that are NOT in es6, es7, es8

### ISSUE THREAD

**Issue by thelordgabo** [you-dont-need/You-Dont-Need-Lodash-Underscore#97]
I am totally agree using native functions like filter, map, reduce, findIndex,  etc over the lodash ones, but I found useful some lodash functions like:

1. _.has() 
let test1 = {
  a: {
    b:{
      c: {
        d: 56
      }
    }
  }
}
// es6:
if(test1 && test1.a && test1.a.b && test1.a.b.c && test1.a.b.c.d){console.log('foo')}
// lodash:
_.has(test1, 'a.b.c.d')
2. _.chunk()
3. _.isPlainObject()
4. _.flatten()
5. _.groupBy()

There are many others, I just listed the ones I used.

**Comment by stevemao** [comment]
We never said that none of the functions are useful. The point of this project is to not over use some modules like lodash/underscore and we see a lot of people do.

**Comment by cht8687** [comment]
thanks for sharing your knowledge @thelordgabo !
